# Site Configuration
base_url = "https://example.com"
title = "Hexdump0"
description = "Site"

# Feeds
generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]

# Taxonomies
taxonomies = [{ name = "tags", feed = true }]

# Build options
compile_sass = false
build_search_index = false

# Markdown settings
[markdown]
bottom_footnotes = true
render_emoji = true



# Custom variables
[extra]
main_section = "posts"
author = "Your Name"

[extra.socials]
# The icons use Simple Icons names: https://simpleicons.org/
pgp_key = "#"

links = [
    { name = "Discord", url = "#" , icon = "discord" },
    { name = "Matrix", url = "#" , icon = "matrix" },
    { name = "Mail", url = "#" , icon = "maildotru" },
    'sep',
    { name = "GitHub", url = "#" , icon = "github" },
    { name = "GitLab", url = "#" , icon = "gitlab" }

]

[extra.navbar]
name = ["Hexdump", "0"]
items = [
  { name = "About", path = "/", default = true },
  { name = "Blog", path = "/blog" },
  { name = "Socials", path = "/socials" },
]
