# Site Configuration
base_url = "https://example.com"
title = "Hexdump0"
description = "Site"

# Taxonomies
taxonomies = [
  { name = "tags"},
  { name = "examples" }
]

# Feeds
generate_feeds = false
feed_filenames = ["atom.xml", "rss.xml"]

# Build options
compile_sass = false
build_search_index = false

# Markdown settings
[markdown]
external_links_target_blank = true
smart_punctuation = true
bottom_footnotes = true
render_emoji = true

[markdown.highlighting]
theme = "dark-plus"

# Theme settings
[extra]

[extra.home]
text = "Hello I'm HexDump0, a random guy who likes to write, hack stuff (web for now) and rant about stupid stuff."
subtext = ' -"My crime is that of curiosity."'

[extra.socials]
# The icons use Simple Icons names: https://simpleicons.org/
pgp_key = "#"

links = [
    { name = "Discord", url = "#" , icon = "discord" },
    { name = "Matrix", url = "#" , icon = "matrix" },
    { name = "Mail", url = "#" , icon = "maildotru" },
    'sep',
    { name = "GitHub", url = "#" , icon = "github" },
    { name = "GitLab", url = "#" , icon = "gitlab" }

]

[extra.navbar]
name = ["Hexdump", "0"]
items = [
  { name = "About", path = "/", default = true },
  { name = "Blog", path = "/blog" },
  { name = "Socials", path = "/socials" },
]

[extra.footer]
text = "Trust None"
