name = "hexdump"
description = "The theme I use for my website"

license = "MIT"
homepage = "https://hexdump.pw"
min_version = "0.22.0"
demo = "https://hexdump.pw"

[author]
name = "HexDump0"
homepage = "https://hexdump.pw"


# Theme settings
[extra]

[extra.home]
text = "Hello I'm HexDump0, a random guy who likes to write, hack stuff (web for now) and rant about stupid stuff."
subtext = ' -"My crime is that of curiosity."'

[extra.socials]
# The icons use Simple Icons names: https://simpleicons.org/
pgp_key = "#"

links = [
    { name = "Discord", url = "#" , icon = "discord" },
    { name = "Matrix", url = "#" , icon = "matrix" },
    { name = "Mail", url = "#" , icon = "maildotru" },
    'sep',
    { name = "GitHub", url = "#" , icon = "github" },
    { name = "GitLab", url = "#" , icon = "gitlab" }

]

[extra.navbar]
name = ["Hexdump", "0"]
items = [
  { name = "About", path = "/", default = true },
  { name = "Blog", path = "/blog" },
  { name = "Socials", path = "/socials" },
]

[extra.footer]
text = "Trust None"
