name = "hexdump"
description = "The theme I use for my website"

license = "MIT"
homepage = "https://hexdump.pw"
min_version = "0.22.0"
demo = "https://hexdump.pw"

[author]
name = "HexDump0"
homepage = "https://hexdump.pw"

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

[extra.navbar]

name = ["Hexdump","0"] # The second item will have a different color

items = [
  { name = "About", url = "/", default = true },
  { name = "Blog", url = "/blog" },
  { name = "Socials", url = "/socials" },
]
